package entity;

public enum ParametroChave {
	FUNC_QUANTIDADE_HORAS_MAXIMA_DIA,
	FUNC_QUANTIDADE_HORAS_MINIMA_DIA,
	FUNC_QUANTIDADE_REGISTROS_MAXIMA_DIA,
	FUNC_QUANTIDADE_REGISTROS_MINIMA_DIA;
}
